### ISSUE TITLE
746. Min Cost Climbing Stairs

### ISSUE THREAD

**Issue by DonXavierdev** [DonXavierdev/Leetcode-Solutions#2]

**Comment by DonXavierdev** [comment]
hi

**Comment by DonXavierdev** [comment]
unable to find algorithm

**Comment by DonXavierdev** [comment]
You are given an integer array cost where cost[i] is the cost of ith step on a staircase. Once you pay the cost, you can either climb one or two steps.

You can either start from the step with index 0, or the step with index 1.

Return the minimum cost to reach the top of the floor.

**Comment by DonXavierdev** [comment]
Example 1:

Input: cost = [10,15,20]
Output: 15
Explanation: You will start at index 1.
- Pay 15 and climb two steps to reach the top.
The total cost is 15.

**Comment by DonXavierdev** [comment]
Example 2:

Input: cost = [1,100,1,1,1,100,1,1,100,1]
Output: 6
Explanation: You will start at index 0.
- Pay 1 and climb two steps to reach index 2.
- Pay 1 and climb two steps to reach index 4.
- Pay 1 and climb two steps to reach index 6.
- Pay 1 and climb one step to reach index 7.
- Pay 1 and climb two steps to reach index 9.
- Pay 1 and climb one step to reach the top.
The total cost is 6.

**Comment by mathew-alex** [comment]
@DonXavierdev  - solve at least one test case, and commit the solution

**Comment by DonXavierdev** [comment]
cost.append(None)
        val=0
        for i in range(len(cost)):
            if cost[i+1]==None or cost[i+2]==None:
                return val
            val+=cost[i]
            if cost[i+1]<cost[i]:
                val-=cost[i]

**Comment by mathew-alex** [comment]
logic would be to pick a position and find the least expensive route to get there. then take the next position and calculate the same. 
Eg: position 1: expense to get to position 1

**Comment by DonXavierdev** [comment]
CODE:
val=0
    for i in range(2,len(cost),2):
        if cost[i-2]+cost[i]<cost[i-1]:
            val+=cost[i-2]+cost[i]
        else:
            val+=cost[i-1]
return val
*********************************************************************************************************
Submission Detail:
144 / 283 test cases passed.
Input:[0,0,1,1]
Output:0
Expected:1

**Comment by mathew-alex** [comment]
val = [0] * len(cost)-1
val[0], val[1] = cost[0], cost[1]
for i in range(2, len(cost)):
    val[i] = min(cost[i-1], cost[i-2]+cost[i])
return min(val[-1], val[-2])
